# This is a basic workflow to help you get started with Actions

name: deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ansible
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          BUCKET_ACCESS_KEY: ${{ secrets.BUCKET_ACCESS_KEY }}
          BUCKET_SECRET_KEY: ${{ secrets.BUCKET_SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d "\r" > ~/.ssh/priv.key
          chmod 0700 ~/.ssh
          chmod 0600 ~/.ssh/priv.key
          ansible-playbook -i hosts --private-key ~/.ssh/priv.key main.yml
        working-directory: "./ansible"
  task-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16' 
      - name: build kosenctfx-cli
        run: go install github.com/theoremoon/kosenctfx/scoreserver/cmd/kosenctfx-cli@latest
      - name: run kosenctfx-cli
        env:
          KOSENCTFX_TOKEN: ${{ secrets.KOSENCTFX_TOKEN }}
          KOSENCTFX_URL: ${{ secrets.KOSENCTFX_URL }}
        run: |
          kosenctfx-cli -dir "challenge" -hashfile challenges.hash -token "$KOSENCTFX_TOKEN" -url "$KOSENCTFX_URL"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update challenges.hash
          commit_options: '--no-verify --signoff'
          file_pattern: challenges.hash
          skip_dirty_check: true    
