stages:
  - deploy

run_ansible:
  stage: deploy
  image: python:3.8
  before_script:
    - pip install ansible
  script:
    - cd ansible
    - export ANSIBLE_CONFIG=$(pwd)
    - bash ./run.bash
  only:
    - master

update_challenge:
  stage: deploy
  image: golang:latest
  before_script:
    - '[ -z "${KOSENCTFX_URL+x}" ] && exit'
    - go get github.com/theoremoon/kosenctfx/scoreserver/cmd/kosenctfx-cli
  script:
    - kosenctfx-cli -dir "challenge" -hashfile challenges.hash -token "$KOSENCTFX_TOKEN" -url "$KOSENCTFX_URL"
    - git config user.name "$GITLAB_USER_ID"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git remote set-url origin "https://gitlab-ci-token:${GITLAB_API_ACCESS_TOKEN}@${CI_REPOSITORY_URL##*@}"
    - git checkout "$CI_COMMIT_REF_NAME"
    - git add .
    - |-
      if [ $(git status -s | wc -l) -gt 0 ]; then
        git commit -m "update challenge checksum"
        git push --push-option=ci.skip origin "$CI_COMMIT_REF_NAME"
      fi
  only:
    - master

