- name: create node_exporter group
  group:
    name: node_exporter
    system: true
    state: present

- name: create node_exporter user
  user:
    name: node_exporter
    system: true
    shell: "/usr/sbin/nologin"
    group: node_exporter
    createhome: false

- name: check is node_exporter already installed
  stat:
    path: /usr/local/bin/node_exporter
  register: node_exporter_bin

- block:
  - name: download node_exporter release
    unarchive:
      src: "https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.{{ arch }}.tar.gz"
      dest: "/tmp"
      remote_src: yes

  - name: place node_exporter binary
    copy:
      src: "/tmp/node_exporter-{{version}}.{{arch}}/node_exporter"
      dest: "/usr/local/bin/node_exporter"
      mode: 0755
      owner: root
      group: root
      remote_src: yes

  when: not node_exporter_bin.stat.exists

- name: place systemd unit file
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
    owner: root
    group: root
    mode: 0644

- name: start node_exporter unit file
  systemd:
    name: "node_exporter.service"
    state: started
    daemon_reload: yes
    enabled: yes

