# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "server1" do |srv|
    srv.vm.box = "ubuntu/focal64"
    srv.vm.network "private_network", ip: "192.168.99.11"
  end

  config.vm.define "server2" do |srv|
    srv.vm.box = "ubuntu/focal64"
    srv.vm.network "private_network", ip: "192.168.99.12"
  end

  config.vm.define "monitor" do |srv|
    srv.vm.box = "ubuntu/focal64"
    srv.vm.network "private_network", ip: "192.168.99.101"
  end
end
