- name: Include Bucket configration variable
  include_vars:
    file: "../../../bucket.yml"
    name: bucket

- name: get accesskey / secret key
  set_fact:
    bucket_access_key: "{{ lookup('env', 'BUCKET_ACCESS_KEY') }}"
    bucket_secret_key: "{{ lookup('env', 'BUCKET_SECRET_KEY') }}"

- name: Place sendtobucket script
  template:
    src: "sendtobucket.j2"
    dest: "/usr/bin/sendtobucket"
    owner: root
    group: root
    mode: "0755"
