- hosts: all
  become: yes
  roles:
    - common
    - user

- hosts: challenges
  become: yes
  roles:
    - sendtobucket
    - docker
    - iptables

- hosts: web
  become: no
  remote_user: "{{ username }}"
  tasks:
    - include_role:
        name: challenge
      async: 300
      poll: 0
      with_items: []
      loop_control:
        loop_var: "challenge"

